spring:
  application:
    name: jiguang-sdk

server:
  port: 9543

logging:
  level:
    root: debug

jiguang:
  api:
    app-key: b266cd5c8544ba09b23733e3
    master-secret: ecf3b3327000abce4764f86e
    dev-key: e2dc75e97486529205528b2a
    dev-secret: e219e2f001df2fe4f08b675e


